version: 2.1

jobs:
    build:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout

workflows:
    version: 2.1
    main:
        jobs:
            - build:
